# Generated by Django 5.1.7 on 2025-05-18 10:49
import django.db.models.deletion
from django.db import migrations, models

def populate_categories_for_fk(apps, schema_editor):
    RequestPost = apps.get_model('requests', 'RequestPost')
    RequestCategory = apps.get_model('requests', 'RequestCategory')
    db_alias = schema_editor.connection.alias

    for post in RequestPost.objects.using(db_alias).all():
        # At this stage, 'post.category' refers to the original CharField value
        # from migration 0001_initial.
        # The actual database column still holds the string.
        # The 'apps.get_model' provides a historical version of the model
        # that should have 'category' as a CharField if this RunPython
        # operation is placed correctly before 'category' is removed or altered.
        # For this to work, 'category_temp_fk' must be added first,
        # then this function runs, then old 'category' is removed.

        category_name_str = post.category 
        
        if category_name_str and isinstance(category_name_str, str) and category_name_str.strip():
            # Get or create the RequestCategory object
            category_obj, created = RequestCategory.objects.using(db_alias).get_or_create(name=category_name_str.strip())
            # Assign the FK to the temporary field
            post.category_temp_fk = category_obj 
            post.save(update_fields=['category_temp_fk'])
        else:
            # If the old category name was empty, blank, or None, ensure the new FK is None
            if post.category_temp_fk is not None: # only save if change needed
                post.category_temp_fk = None
                post.save(update_fields=['category_temp_fk'])

class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Request Categories',
            },
        ),
        migrations.AddField(
            model_name='requestpost',
            name='category_temp_fk', # Temporary ForeignKey field
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='request_posts', # Use the final related_name
                to='requests.requestcategory'
            ),
            # preserve_default=False # Add this if AddField complains about defaults for existing rows
        ),
        migrations.RunPython(populate_categories_for_fk, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='requestpost',
            name='category', # Remove the old CharField
        ),
        migrations.RenameField(
            model_name='requestpost',
            old_name='category_temp_fk',
            new_name='category', # Rename the temporary FK to the final name 'category'
        ),
    ]
